"""WORKSPACE file for SEAL."""

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")#,"new_http_archive",)


load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

#https://github.com/bazelbuild/rules_go/blob/0.19.0/go/workspace.rst#proto-dependencies
git_repository(
    name = "com_google_protobuf",
    commit = "09745575a923640154bcf307fba8aedff47f240a",
    remote = "https://github.com/protocolbuffers/protobuf",
    shallow_since = "1558721209 -0700",
)

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()


#https://chromium.googlesource.com/external/github.com/google/quic-trace/+/refs/heads/master/WORKSPACE

http_archive(
    name = "zlib",
    build_file = "@com_google_protobuf//:third_party/zlib.BUILD",
    sha256 = "c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1",
    strip_prefix = "zlib-1.2.11",
    urls = ["https://zlib.net/zlib-1.2.11.tar.gz"],
)

#https://docs.nvidia.com/isaac/archive/2019.2/doc/faq.html 
# new_http_archive(
#     name = "zlib",
#     # build_file = clean_dep("//zlib.BUILD"),
#     sha256 = "c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1",
#     strip_prefix = "zlib-1.2.11",
#     url = "https://zlib.net/zlib-1.2.11.tar.gz",
# )

# load()

# bind(
#     name = "zlib",
#     actual = "@net_zlib//:zlib",
# )
